version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  - package-ecosystem: "npm"
    directory: "/deploy"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  - package-ecosystem: "npm"
    directory: "/webapp"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope" 
