name: "Setup"
description: "Set up node environment and install dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: "./.nvmrc"
        cache-dependency-path: "**/package-lock.json"
        cache: "npm"

    - uses: actions/cache@v3
      id: webapp_cache
      with:
        path: "./webapp/node_modules"
        key: modules-${{ hashFiles('./webapp/package-lock.json') }}

    - name: Install webapp dependencies
      if: steps.webapp_cache.outputs.cache-hit != 'true'
      run: npm ci --legacy-peer-deps --prefer-offline --no-audit
      working-directory: ./webapp
      shell: "bash"

    - uses: actions/cache@v3
      id: github_actions_bin_cache
      with:
        path: "./.github/actions/bin/node_modules"
        key: modules-${{ hashFiles('./.github/actions/bin/package-lock.json') }}

    - name: Install github actions dependencies
      if: steps.github_actions_bin_cache.outputs.cache-hit != 'true'
      run: npm ci --legacy-peer-deps --prefer-offline --no-audit
      working-directory: ./.github/actions/bin
      shell: "bash"
