name: Build Ladle
run-name: Updating Ladle component library
on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  build:
    if: github.event.pull_request.merged == true
    defaults:
      run:
        working-directory: ./webapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - uses: "./.github/actions/npm-setup"
      - name: Build components
        run: npm run ladle:build -- --outDir "../docs"
      - name: Update components
        run: |
          cd ..
          ls -Qa | grep -v docs | grep -v "\.\." | grep -v "^\".\"$" | grep -v "\".git" | xargs rm -rf
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git fetch origin gh-pages
          git checkout gh-pages
          git reset --hard
          rsync -a ./docs ./
          rm -rf ./docs
          git add --all
          git reset -- .github
          git commit -m "feat: update component library"
          git push origin
