name: Code Health
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  check-types:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@v3
      - id: setup
        uses: "./.github/actions/npm-setup"
      - run: npm run check:typescript

  check-eslint:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@v3
      - id: setup
        uses: "./.github/actions/npm-setup"
      - run: npm run check:eslint

  check-prettier:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@v3
      - id: setup
        uses: "./.github/actions/npm-setup"
      - run: npm run check:prettier

  test:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@v3
      - id: setup
        uses: "./.github/actions/npm-setup"
      - run: cp .env.ogp.test.levelworks.dev .env
      - run: npm run test
