name: Code Health
on: [push]
jobs:
  check-types:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@v3
      - id: setup
        uses: "./.github/actions/npm-setup"
      - run: npm run check:typescript

  check-eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@v3
      - id: setup
        uses: "./.github/actions/npm-setup"
      - run: npm run check:eslint

  check-prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@v3
      - id: setup
        uses: "./.github/actions/npm-setup"
      - run: npm run check:prettier

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@v3
      - id: setup
        uses: "./.github/actions/npm-setup"
      - run: cp .env.ogp.test.levelworks.dev .env
      - run: npm run test
