name: "PR check"
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  feature-or-fix-branch-naming-rules:
    runs-on: ubuntu-latest
    if: |
      startsWith(github.head_ref, 'feature') ||
      startsWith(github.head_ref, 'hotfix') ||
      startsWith(github.head_ref, 'bugfix')
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '[a-z]+\/(LEV|LW1)-[0-9]+-\S+'
          allowed_prefixes: 'feature,bugfix,hotfix'

  release-branch-naming-rules:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release')
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '[a-z]+\/v[0-9]+.[0-9]+.[0-9]+'
          allowed_prefixes: 'release'

  creative-friday-branch-naming-rules:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'creative-friday')
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '[a-z]+\/\S+'
          allowed_prefixes: 'creative-friday'

  dependabot-branch-naming-rules:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'dependabot')
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '[a-z]+\/\S+'
          allowed_prefixes: 'dependabot'

  unknown-branch-naming-rules:
    needs:
      - feature-or-fix-branch-naming-rules
      - release-branch-naming-rules
      - creative-friday-branch-naming-rules
      - dependabot-branch-naming-rules
    runs-on: ubuntu-latest
    if: always() && needs.feature-or-fix-branch-naming-rules.result == 'skipped' &&  needs.release-branch-naming-rules.result == 'skipped' && needs.creative-friday-branch-naming-rules.result == 'skipped' && needs.dependabot-branch-naming-rules.result == 'skipped'
    steps:
      - run: |
          cat <<'END'
          Branch name does not adhere to standards. Following branch name patterns are allowed:
            (bugfix|hotfix|feature)/(LEV|LW1)-NUMBER-description
            release/vX.Y.Z
            creative-friday/description
          END
          exit 1

  title-check:
    runs-on: ubuntu-latest
    if: |
      startsWith(github.head_ref, 'feature') ||
      startsWith(github.head_ref, 'hotfix') ||
      startsWith(github.head_ref, 'bugfix')
    steps:
      - uses: thehanimo/pr-title-checker@v1.3.6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          configuration_path: ".github/pull-request-title-checker-config.json"
