run-name: Tag release
on:
  push:
    branches:
      - main
jobs:
  create_tag:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          # needed otherwise no merge base can be found
          fetch-depth: 0

      - name: show me
        run: |
          echo ${{ github.ref }}

