run-name: Tag release
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  create_tag:
    if: github.event.pull_request.merged == true
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          # needed otherwise no merge base can be found
          fetch-depth: 0

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Set release tag
        run: echo "TAG=$(echo ${{ github.ref }} | tr -d 'release/')" >> $GITHUB_ENV

      - name: show me
        run: |
          git status
          git log --pretty=format:\"%h %ad | %s%d [%an]\" --graph --date=short

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          body: See CHANGELOG.md

