run-name: Tag release
on:
  push:
    branches:
      - main
jobs:
  create_tag:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - name: show me
        run: |
          echo ${{ github.ref }}

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          # needed otherwise no merge base can be found
          fetch-depth: 0

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Set release tag
        run: echo "TAG=$(echo ${{ github.ref }} | tr -d 'release/')" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          body: See CHANGELOG.md

